{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mc2d
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mc2d_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mc2d/mc2d_{{ version }}.tar.gz
  sha256: be27fcc1fb43c3f3fd4d1e443c1ff44dc90eba83852b56526b9489ba4b517b1a

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-ggpubr
    - r-mvtnorm
  run:
    - r-base
    - r-ggplot2
    - r-ggpubr
    - r-mvtnorm

test:
  commands:
    - $R -e "library('mc2d')"           # [not win]
    - "\"%R%\" -e \"library('mc2d')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mc2d
  license: GPL-2.0-or-later
  summary: A complete framework to build and study Two-Dimensional Monte-Carlo simulations, aka Second-Order Monte-Carlo simulations. Also includes various distributions (pert, triangular, Bernoulli, empirical discrete and continuous).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
