travis:
  secure:
    BINSTAR_TOKEN: goafEH+fMotgk/lerIWiMUShXoFD7BdJCmcDMjW4NmDaFQG1Ud7wYmwF/fcxgGqgNMEtedhsf8892/N6r6fWsJ54nZuhL5bKwXv/pEAMm5f9TTFHOIrF9n6JaQfVZ5y40H1YBVf38si0EkY5Qhuh8OxXT5ntmeyJLvpCc1QVTOKxuO8ZXELzXatMxQ3SEFFMFknsYymry5bmM1vtn7LfAVghdcRwJqZ8RP6rXdDpKiiM48nz/aWRucfGoL5aemQe3re6UjFJ/Oi4/tj+O5LJpvMxNfAVDMXSn8LQbsWbFeT/UKMUUFCmBS1seJ2QtDRsCDLlo+t7j/C+bZdrr8PAXROxhBKiaLYPvtR11cmYcyF7moVoiUypIUL0BFDvpB4SbS2szbD9t2q1pc1uYMm9qcY6U8qgGCG2GLmE+Tf4IktahbWvHycW25st5yVgwgIo3tiboYT6DqLEetKjIIfIoZCLzEjFZLFAgB8wcb3eHO2Yrqtom1tcssDqQlwSJMtsUniqZcSJ3bYnvEVreI4OmN3KHQww7PYZO4loCOxSKvJBoCuqYNNTucOpO9nwdTEYyl1AahTXmUq3xiwoNIQdDB1M54KbnMfLglhXMtUGugLGz/aZvcTIXRKyRWrLQlt3TZYYna6p62tSP6mTim9gogaql43Yst1MLgPe4AHgEpg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
