travis:
  secure:
    BINSTAR_TOKEN: kjIrzkZbTyBDFxB/MUhcwPxDZaE56WeN7NNDGakG5tpaxoG4mPu8rdOVT2ohC6QfZXF+F4MmAEG3qHC4YG/c7/hOuYq3Q9SUxrZAiyg8DbBM6p67ZQHvQrWDhJyFULOSDfnxQQ1m1LZRGp43mF7IHFsniF/p1yRGNL2B+LBxKDbNx5teyHtnGUkVdbLAkkWOZlp6VuubwZLq7js5q7yJECE6sqi0sEJ3W78ur70TZmafF4UvYTIpAplZ1n/00xgZnlLbRGpejqVleKtuoh2sZMGVB/P1jwaFqmGYC8ESqGIEYMp4r8U9PSJ1j/cRPHTUowv0tL2We4/Wedxcc22LzdGMIaU0wNpPYrbcKHiBEzbuazSQhvA7zdGyzW+PoTkqiPFtzt2AWfZ/e/H/zufs8RxdcUmRpguqiaLBaS7EI1geW8FksyRjhlFYecegFcgPt6KS8ofNK0UszB4sdiScgDYYESHyZtSzwt7xGifAzH2HEgyqXsuM4Zp/mxdGgDVyFCWGKUvxgx8uPWj1kqkd98jR54WPQNClR9uQLg5Ix/6y9FXbSY6tvyN4xeo/kX7fV5UBAD2R1SaMMZd2h/rx+Cu6HAmgF9mEPTOYTlQzE3fjR/DAserGg6vmEUD57O7fYL8n7swUXRFqQpysP46IIy5aBOMrjvoI0AraRrk+WoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
