appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: njK1T10o3NUuhlQhseiY5+jfoQl06qJM4MYkUs0N4a+W1Sm8LviPkjcoadpa16PhzmDGcVjiXF7KrKNi7YsfC7YZu7Vz4UXcueAY15M99TXSO4HfeeKFdClwQVTQTR/IMO+b7FQer0WawMx2lXk0diqhT4hHUlPsoOpwU62kqj24OgknSp5LlmXWBaCik4Cr9Rb4LlDs4fEjDMwjLQbR9qpthWmYDb1YQteANjUWOTRs9vklkHavma/Z1wM7kdVUQuuhzq2oeMb4sa1i+l5UK4HxZTggmZOIGdvLZMJgJOZoYSjOzEjHXjNLJD0qVTbHtOb0P7SoZ93sAdSmrX/OLZ8yXplME/sQIs5aBTQ4gRK7a4eXrxcWngqpOnPaFkTtA/OSeyroN40XYUnCbnDUsdOc0HFtURJ+ZK1aYQzMw+M0LJZnkgPVHqSKCNMPvHLnRQYRC29v21GnjG10MqCIQCloHzXVHvJlBRf5vyxX9owamJO9fcKzYwlHHL+iFBzExFqwfv+8jA6UCQjZP0ZcJxS/4JVQdPugMJRrMd5jtbQhRKQZvH38305IjtXdcilLvfB+a6xt6SksxpIV93MwKdJPgmMaEqGbDecXu7qlaHjT1H/sRe1EQwHPhH3c66OE7R0ZdZQDSJRygQqoi/IajJ4M9QY+Ji6AZq2bNHqVVkk=}
