travis:
  secure:
    BINSTAR_TOKEN: QGggQfrr+A4IfEL1uIdF30aToJEHRU3Oif8wgaecTQzoOIgFUBPnskRiYlA9td6uKXIJLPkUxBZJg0y3HgUSmbETmss/DnLoGJ3qHHKshfMc15R8vjklx9c45tOWFrvyrQixFdxkdDirzbHxKkK+O7Xr3/LZPpElz3C7KlWL6DEmY7vdFZAolJRNC2CWQR8lafH6CxoPtgpe+xZpGJmiPRy7iK6O31+MnAa81X4kE5Mw2BFQfG2gcBAEIa+BF+YKwyCBXWoNqYmz15+Rt2k88sVNM46918q/w10UKO5FqPl8GKP5Jn+XqgHIXZTpn3FRS6v1oQh6a7nCFoyhThV0FhZMLl0RMmzX9xPyucN8ex6+k4MhpNi3pUq5PVFuEfKrXy3ZkBQdG+Armfet8+XagK1nDQIb4pXtdBGPtMqFf2knaBA64zkNhaOpcKJVZrnRfyoBl/dHSrg+zgeZ6Ox6sd1QmnJVnBLokWO7CxmXSFpztEBKPbBeCwMxmkQwP4tepjt5v+4fRjKHShWJTO4qbm6C24U9kV55mxffenm5AnAx44AvmZWVDkfSezjOqLLp2lW/SqLpjWrSJ18DsTeFP6HBjqIone1fN/h0ykzebQJaoGJvFAoHs1Vqec5QFqYQ4FWC+cu7R6KIKymV5NxOY9oDUpaznNqnJvYHwyvSUHM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
